pipeline {
    agent any
    environment {
        PROJECT_ID = 'journeyiq-prod'
        booking-service = 'booking-service'
        IMAGE_TAG = "us-central1-docker.pkg.dev/${PROJECT_ID}/journeyiq-services/${booking-service}:${BUILD_NUMBER}"
    }
    stages {
        stage('Test') {
            steps {
                sh 'pip install -r requirements.txt && pytest'
            }
        }
        stage('Build') {
            steps {
                sh "docker build -t ${IMAGE_TAG} ."
            }
        }
        stage('Push') {
            steps {
                sh "docker push ${IMAGE_TAG}"
            }
        }
        stage('Deploy') {
            steps {
                script {
                    sh "cd ../../k8s/overlays/prod/${booking-service} && kustomize edit set image ${IMAGE_TAG} && kustomize build . | kubectl apply -f -"
                }
            }
        }
    }
    post {
        failure {
            echo 'Deployment failed. Triggering rollback...'
            // Rollback logic: kubectl rollout undo deployment/${booking-service}
            sh "kubectl rollout undo deployment/${booking-service}"
        }
    }
}
