steps:
  # 1. Run Tests (in docker)
  - name: 'python:3.11-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt && \
        pip install pytest && \
        # Mock test command for contract - real tests would run here
        echo "Running tests..."

  # 2. Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/journeyiq-services/auth-service:${SHORT_SHA}', '.']

  # 3. Push Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/journeyiq-services/auth-service:${SHORT_SHA}']

  # 4. Deploy to GKE (using Kustomize)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Install Kustomize (if not in builder, or use gke-deploy)
        # For this contract, we simulate the kustomize edit + apply flow
        cd ../../k8s/overlays/prod/auth-service
        kustomize edit set image us-central1-docker.pkg.dev/${PROJECT_ID}/journeyiq-services/auth-service:${SHORT_SHA}
        kustomize build . | kubectl apply -f -

substitutions:
  _REGION: us-central1

images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/journeyiq-services/auth-service:${SHORT_SHA}'
